[package]
name = "synpy"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name = "synpy_rust"
crate-type = ["cdylib"]

[dependencies]
bitvec = "1.0.1"
pyo3 = "0.27.1"
pyo3-ffi = "0.27.2"
synir = { path = "../synir" }
